name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: liauser
          POSTGRES_PASSWORD: liapassword
          POSTGRES_DB: liadb
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://liauser:liapassword@localhost:5432/liadb

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client \
              libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              file \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev

      - name: Wait for PostgreSQL to start
        run: sleep 10

      - name: Build
        run: |
          cd lia-src
          cargo install sqlx-cli --no-default-features --features postgres
          cd back-end
          sqlx migrate run
          cd ..
          cargo build

      - name: Run tests
        run: |
          cd lia-src
          cargo test